import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildApplicationPackage } from '../application-package.mjs';

const base = (classification = 'apply', extra = {}) => ({ schema_version: 1, source: { task_id: 'linkedin-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', artifact_sha256: 'source-hash' }, jobs: [{ linkedin_job_id: '4436442782', url: 'https://www.linkedin.com/jobs/view/4436442782/', title: 'Senior Executive – Corporate Development – Remote, Part Time', company: 'Harris Computer', location: 'Colorado, United States (Remote)', classification, fit_assessment: { score: 4, rationale: 'Documented transaction and executive operating leadership fit.' }, relevant_candidate_evidence: ['Edge Energy acquisition and divestiture leadership.'], material_gaps: ['Software acquisition depth is not directly documented.'], processing: { approved: classification === 'apply' }, ...extra }] });
const enrichment = { schema_version: 1, jobs: [{ linkedin_job_id: '4436442782', jd_retrieval_status: 'complete', evaluation_ready: true, jd_text: 'Complete rendered Harris Computer job description.' }] };
function setup() { const root = mkdtempSync(join(tmpdir(), 'career-ops-package-')); const resume = join(root, 'resume.pdf'); writeFileSync(resume, 'pdf'); return { root, resume }; }

test('approved Apply creates a deterministic review package without Applied status', () => { const { root, resume } = setup(); const result = buildApplicationPackage({ evaluation: base(), enrichment, jobId: '4436442782', candidateEvidence: 'authoritative cv evidence', resumePath: resume, outputRoot: root, now: '2026-09-11T00:00:00.000Z' }); assert.equal(result.status, 'package_ready'); const manifest = JSON.parse(readFileSync(result.manifest_path)); assert.equal(manifest.package_status, 'package_ready'); assert.equal(manifest.submitted, false); assert.match(readFileSync(result.report_path, 'utf8'), /Not Applied/); });
test('Consider and Reject cannot create packages', () => { for (const classification of ['consider', 'reject']) { const { root, resume } = setup(); assert.throws(() => buildApplicationPackage({ evaluation: base(classification), enrichment, jobId: '4436442782', candidateEvidence: 'evidence', resumePath: resume, outputRoot: root }), /approved final Apply/); } });
test('missing authoritative JD or candidate evidence fails closed', () => { const { root, resume } = setup(); assert.throws(() => buildApplicationPackage({ evaluation: base(), enrichment: { schema_version: 1, jobs: [] }, jobId: '4436442782', candidateEvidence: 'evidence', resumePath: resume, outputRoot: root }), /complete authoritative JD/); assert.throws(() => buildApplicationPackage({ evaluation: base(), enrichment, jobId: '4436442782', candidateEvidence: '', resumePath: resume, outputRoot: root }), /candidate evidence/); });
test('ineligible primary-search evaluation cannot create an Apply package', () => { const { root, resume } = setup(); const primary_search_eligibility = { eligible: false, result: 'ineligible' }; assert.throws(() => buildApplicationPackage({ evaluation: base('apply', { primary_search_eligibility }), enrichment, jobId: '4436442782', candidateEvidence: 'evidence', resumePath: resume, outputRoot: root }), /primary-search eligibility/); });
test('replay is deterministic for the same inputs', () => { const { root, resume } = setup(); const args = { evaluation: base(), enrichment, jobId: '4436442782', candidateEvidence: 'evidence', resumePath: resume, outputRoot: root, now: '2026-09-11T00:00:00.000Z' }; const one = buildApplicationPackage(args); const two = buildApplicationPackage(args); assert.deepEqual(one, two); });
