import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { HANDOFF_LABEL, receiveIssue, receiveOnce } from '../github-handoff-receiver.mjs';

const body = (id = 'github-test-001', extra = '') => `Human context\n\n\`\`\`yaml\nhandoff_id: ${id}\nschema_version: 1\n${extra}\`\`\`\n`;
const issue = (overrides = {}) => ({ number: 42, url: 'https://github.com/example/repo/issues/42', title: 'Career Ops Handoff — Example — Role', body: body(), labels: [{ name: HANDOFF_LABEL }], ...overrides });
function setup() { const root = mkdtempSync(join(tmpdir(), 'career-ops-github-receiver-')); mkdirSync(join(root, 'data'), { recursive: true }); return root; }
function clean(root) { rmSync(root, { recursive: true, force: true }); }
const options = rootDir => ({ rootDir, repository: 'example/repo', now: () => '2026-09-04T12:00:00.000Z' });

test('valid labeled handoff Issue creates an inbox file', () => { const root=setup(); try { const result=receiveIssue(issue(),options(root)); assert.equal(result.status,'received'); assert.match(readFileSync(join(root,'data/handoff-inbox/github-test-001.yml'),'utf8'),/schema_version: 1/); } finally { clean(root); } });
test('unlabeled Issue is ignored', () => { const root=setup(); try { const result=receiveIssue(issue({labels:[]}),options(root)); assert.equal(result.status,'ignored'); assert.equal(result.reason,'missing career-ops-handoff label'); } finally { clean(root); } });
test('malformed YAML is blocked', () => { const root=setup(); try { const result=receiveIssue(issue({body:'```yaml\nhandoff_id: [\n```'}),options(root)); assert.equal(result.status,'blocked_invalid_issue'); assert.match(result.error,/malformed YAML/); } finally { clean(root); } });
test('missing YAML block is blocked', () => { const root=setup(); try { const result=receiveIssue(issue({body:'Human-readable text only.'}),options(root)); assert.equal(result.status,'blocked_invalid_issue'); assert.match(result.error,/exactly one fenced YAML/); } finally { clean(root); } });
test('missing handoff_id is blocked', () => { const root=setup(); try { const result=receiveIssue(issue({body:'```yaml\nschema_version: 1\n```'}),options(root)); assert.equal(result.status,'blocked_invalid_issue'); assert.match(result.error,/handoff_id is required/); } finally { clean(root); } });
test('same Issue and same payload repeated is a safe no-op', () => { const root=setup(); try { receiveIssue(issue(),options(root)); const result=receiveIssue(issue(),options(root)); assert.equal(result.no_op,true); } finally { clean(root); } });
test('same Issue with changed payload conflicts without overwrite', () => { const root=setup(); try { receiveIssue(issue(),options(root)); const changed=issue({body:body('github-test-001','version: 2\n')}); const result=receiveIssue(changed,options(root)); assert.equal(result.status,'conflict_changed_issue'); assert.doesNotMatch(readFileSync(join(root,'data/handoff-inbox/github-test-001.yml'),'utf8'),/version: 2/); } finally { clean(root); } });
test('existing destination with same contents is safe', () => { const root=setup(); try { mkdirSync(join(root,'data/handoff-inbox'),{recursive:true}); writeFileSync(join(root,'data/handoff-inbox/github-test-001.yml'),'handoff_id: github-test-001\nschema_version: 1\n'); const result=receiveIssue(issue(),options(root)); assert.equal(result.status,'received'); } finally { clean(root); } });
test('existing destination with different contents conflicts', () => { const root=setup(); try { mkdirSync(join(root,'data/handoff-inbox'),{recursive:true}); writeFileSync(join(root,'data/handoff-inbox/github-test-001.yml'),'handoff_id: github-test-001\nschema_version: 99\n'); const result=receiveIssue(issue(),options(root)); assert.equal(result.status,'conflict_destination'); assert.match(readFileSync(join(root,'data/handoff-inbox/github-test-001.yml'),'utf8'),/99/); } finally { clean(root); } });
test('multiple YAML candidate blocks are blocked', () => { const root=setup(); try { const result=receiveIssue(issue({body:`${body()}\n\`\`\`yml\nhandoff_id: second-001\n\`\`\``}),options(root)); assert.equal(result.status,'blocked_invalid_issue'); assert.match(result.error,/more than one/); } finally { clean(root); } });
test('GitHub command output is injected and unlabeled results remain ignored', () => { const root=setup(); try { const gh=(args)=>{ assert.deepEqual(args.slice(0,4),['issue','list','--repo','example/repo']); return JSON.stringify([issue({labels:[]})]); }; const result=receiveOnce({...options(root),gh}); assert.equal(result.status,'idle'); assert.equal(result.results[0].status,'ignored'); } finally { clean(root); } });
test('GitHub CLI failure is returned without mutating inbox', () => { const root=setup(); try { const result=receiveOnce({...options(root),gh:()=>{throw new Error('authentication required');}}); assert.equal(result.status,'github_error'); assert.match(result.error,/authentication required/); } finally { clean(root); } });
test('malformed earlier Issue does not prevent a later valid Issue from being received', () => { const root=setup(); try { const malformed=issue({number:1,body:'```yaml\nhandoff_id: [\n```'}); const valid=issue({number:2,body:body('later-valid-002')}); const result=receiveOnce({...options(root),gh:()=>JSON.stringify([malformed,valid])}); assert.equal(result.status,'blocked'); assert.deepEqual(result.results.map(item=>item.issue_number),[1,2]); assert.equal(result.results[0].status,'blocked_invalid_issue'); assert.equal(result.results[1].status,'received'); assert.match(readFileSync(join(root,'data/handoff-inbox/later-valid-002.yml'),'utf8'),/handoff_id: later-valid-002/); } finally { clean(root); } });
test('conflicting earlier Issue does not prevent a later valid Issue from being received', () => { const root=setup(); try { const original=issue({number:1,body:body('original-001')}); receiveIssue(original,options(root)); const changed=issue({number:1,body:body('original-001','version: 2\n')}); const valid=issue({number:2,body:body('later-valid-002')}); const result=receiveOnce({...options(root),gh:()=>JSON.stringify([changed,valid])}); assert.equal(result.status,'blocked'); assert.equal(result.results[0].status,'conflict_changed_issue'); assert.equal(result.results[1].status,'received'); assert.doesNotMatch(readFileSync(join(root,'data/handoff-inbox/original-001.yml'),'utf8'),/version: 2/); assert.match(readFileSync(join(root,'data/handoff-inbox/later-valid-002.yml'),'utf8'),/handoff_id: later-valid-002/); } finally { clean(root); } });
test('multiple valid Issues are processed in deterministic Issue-number order', () => { const root=setup(); try { const later=issue({number:9,body:body('ordered-009')}); const earlier=issue({number:2,body:body('ordered-002')}); const result=receiveOnce({...options(root),gh:()=>JSON.stringify([later,earlier])}); assert.equal(result.status,'received'); assert.deepEqual(result.results.map(item=>item.issue_number),[2,9]); assert.equal(readFileSync(join(root,'data/handoff-inbox/ordered-002.yml'),'utf8').startsWith('handoff_id: ordered-002'),true); assert.equal(readFileSync(join(root,'data/handoff-inbox/ordered-009.yml'),'utf8').startsWith('handoff_id: ordered-009'),true); } finally { clean(root); } });
test('receiver source preserves the transport-only and never-submit boundary', () => { const source=readFileSync(new URL('../github-handoff-receiver.mjs',import.meta.url),'utf8'); assert.doesNotMatch(source,/from ['"]\.\/handoff(?:-runner)?\.mjs['"]/); assert.doesNotMatch(source,/\b(?:importHandoff|buildHandoffReport|insertTrackerRow|submitApplication)\s*\(/); assert.doesNotMatch(source,/\b(?:set-status|prepare-application|application-answers)\.mjs\b/); });
